<a href="https://colab.research.google.com/github/Putrimaesarah/CAPSTONE-DATMIN-KELOMPOK-J/blob/main/CAPSTONE_DATMIN_KELOMPOK_J.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import numpy as np

In [ ]:
import warnings; warnings.simplefilter('ignore')

In [ ]:
!wget -P data https://github.com/Putrimaesarah/CAPSTONE-DATMIN-KELOMPOK-J/blob/main/alumni.csv

--2024-10-24 12:35:32--  https://github.com/Putrimaesarah/CAPSTONE-DATMIN-KELOMPOK-J/blob/main/alumni.csv
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘data/alumni.csv.1’

alumni.csv.1            [  <=>               ] 427.35K  1.87MB/s    in 0.2s

2024-10-24 12:35:32 (1.87 MB/s) - ‘data/alumni.csv.1’ saved [437611]

In [8]:
Data = pd.read_csv("data/alumni.csv", low_memory = False, encoding='utf8')
Data

,Timestamp,Nomor Induk Mahasiswa (NIM),Tahun Masuk UIN Jakarta,Tahun Wisuda,Bulan Wisuda,No HP (WhatsApp):,email,Waktu Mendapatkan Pekerjaan:,Status saat ini:,Tahun Wirausaha,...,Penghasilan,Univeritas,Tahun Masuk Studi Lanjut:,Nama jurusan/program studi setelah Kuliah di FST UIN Jakarta:,Kesesuaian Kurikulum:,Kesesuaian Bidang Ilmu:,Saran,Program Studi,Lama Bekerja di Institusi Saat ini:,Kota tempat bekerja saat Ini
0,07/03/2024 08:09:53,1,2019,2023,Februari,85267511845,1@gmail.com,Belum mendapatkan pekerjaan,Melamar Pekerjaan,NaN,...,NaN,NaN,NaN,NaN,4,4,"Saran, dari prodi membuka kesempatan bekerja s...",Prodi Teknik Pertambangan,NaN,NaN
1,06/04/2024 11:27:37,2,2018,2024,Mei,85267511846,2@gmail.com,Belum mendapatkan pekerjaan,Melamar Pekerjaan,NaN,...,NaN,NaN,NaN,NaN,4,4,NaN,Agribisnis S1,NaN,NaN
2,06/04/2024 11:28:30,3,2018,2024,Mei,85267511847,3@gmail.com,6-12 bulan,Karyawan Swasta,NaN,...,NaN,NaN,NaN,NaN,5,5,NaN,Agribisnis S1,NaN,NaN
3,06/04/2024 11:28:54,4,2017,2024,Mei,85267511848,1@gmail.com,Kurang dari 3 bulan.,Melamar Pekerjaan,NaN,...,NaN,NaN,NaN,NaN,4,4,NaN,Agribisnis S1,NaN,NaN
4,06/04/2024 11:29:03,5,2019,2024,Mei,85267511849,2@gmail.com,Belum mendapatkan pekerjaan,Melamar Pekerjaan,NaN,...,NaN,NaN,NaN,NaN,4,4,NaN,Agribisnis S1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,09/11/2024 13:28:49,431,2020,2024,November,85267512275,2@gmail.com,1,Karyawan Swasta,NaN,...,NaN,NaN,NaN,NaN,4,5,"Adanya program job fair untuk para alumni, yan...",Prodi Teknik Pertambangan,NaN,NaN
431,09/18/2024 15:07:09,432,2019,2024,November,85267512276,3@gmail.com,1,Karyawan Swasta,-,...,3.5,-,-,-,4,5,Alhamdulillah semua berjalan dengan baik. Semo...,Prodi Agribisnis,NaN,NaN
432,10/14/2024 14:49:49,433,2020,2024,November,85267512277,1@gmail.com,Belum mendapatkan pekerjaan,Melamar Pekerjaan,NaN,...,NaN,NaN,NaN,NaN,4,4,saran untuk prodi membuat jadwal seminar supay...,Prodi Agribisnis,NaN,NaN
433,10/15/2024 14:43:58,434,2020,2024,November,85267512278,2@gmail.com,Belum mendapatkan pekerjaan,Melamar Pekerjaan,NaN,...,NaN,NaN,NaN,NaN,4,4,NaN,Prodi Agribisnis,NaN,NaN
434,10/18/2024 12:32:04,435,2020,2025,Agustus,85267512279,3@gmail.com,Belum mendapatkan pekerjaan,NaN,NaN,...,NaN,NaN,NaN,NaN,5,4,NaN,Prodi Agribisnis,NaN,NaN

# Informasi Data

## Data info

In [9]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 23 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   Timestamp                                                       435 non-null    object
 1   Nomor Induk Mahasiswa (NIM)                                     435 non-null    int64
 2   Tahun Masuk UIN Jakarta                                         435 non-null    object
 3   Tahun Wisuda                                                    435 non-null    object
 4   Bulan Wisuda                                                    435 non-null    object
 5   No HP (WhatsApp):                                               435 non-null    int64
 6   email                                                           435 non-null    object
 7   Waktu Mendapatkan Pekerjaan:                                    435 non-null    object
 8   Status saat ini:                                                423 non-null    object
 9   Tahun Wirausaha                                                 46 non-null     object
 10  Bidang wirausaha:                                               47 non-null     object
 11  Perusahaan                                                      230 non-null    object
 12  Posisi                                                          232 non-null    object
 13  Penghasilan                                                     206 non-null    float64
 14  Univeritas                                                      47 non-null     object
 15  Tahun Masuk Studi Lanjut:                                       43 non-null     object
 16  Nama jurusan/program studi setelah Kuliah di FST UIN Jakarta:   44 non-null     object
 17  Kesesuaian Kurikulum:                                           435 non-null    int64
 18  Kesesuaian Bidang Ilmu:                                         435 non-null    int64
 19  Saran                                                           204 non-null    object
 20  Program Studi                                                   435 non-null    object
 21  Lama Bekerja di Institusi Saat ini:                             0 non-null      float64
 22  Kota tempat bekerja saat Ini                                    0 non-null      float64
dtypes: float64(3), int64(4), object(16)
memory usage: 78.3+ KB

## Menghapus variabel